// Default seed data — mirrors current hardcoded content in public pages.
// This data is written to localStorage on first launch if no data exists.

import type {
  HomeContent,
  ServiceItem,
  PortfolioItem,
  Testimonial,
  Brand,
  AboutContent,
  SiteSettings,
} from "./types";

export const defaultHomeContent: HomeContent = {
  heroBadge: {
    en: "Strategy. Brand. Growth.",
    ar: "استراتيجية. علامة. نمو.",
  },
  heroTitleBefore: {
    en: "We build",
    ar: "نبني",
  },
  heroTitleHighlight: {
    en: "growth systems",
    ar: "أنظمة نمو",
  },
  heroTitleAfter: {
    en: "for brands with direction.",
    ar: "لعلامات تتحرك بوضوح.",
  },
  heroSubtitle: {
    en: "Panda is a strategy-led creative agency partnering with ambitious brands to design, launch and scale measurable growth across every channel.",
    ar: "باندا وكالة إبداعية قائمة على الاستراتيجية، نشارك العلامات الطموحة في تصميم وإطلاق وتوسيع نمو قابل للقياس عبر جميع القنوات.",
  },
  heroPrimaryCtaLabel: {
    en: "Start a Project",
    ar: "ابدأ مشروعاً",
  },
  heroPrimaryCtaHref: "/contact",
  heroSecondaryCtaLabel: {
    en: "View Our Work",
    ar: "شاهد أعمالنا",
  },
  heroSecondaryCtaHref: "/portfolio",
  heroStrategyTabs: [
    { id: "tab1", title: { en: "Strategy", ar: "استراتيجية" }, number: "01" },
    { id: "tab2", title: { en: "Content", ar: "محتوى" }, number: "02" },
    { id: "tab3", title: { en: "Media", ar: "إعلانات" }, number: "03" },
  ],
  heroMainImage: "/assets/home/creative-strategy-session.jpg",
  heroSecondaryImage: "/assets/home/campaign-laptop.jpg",
  heroBottomImage: "/assets/home/brand-planning-wall.jpg",
  heroCampaignRoomLabel: {
    en: "Campaign Room",
    ar: "غرفة الحملات",
  },
  heroCampaignItems: [
    { id: "c1", title: { en: "Brand story", ar: "قصة العلامة" }, number: "01" },
    { id: "c2", title: { en: "Content engine", ar: "محرك المحتوى" }, number: "02" },
    { id: "c3", title: { en: "Media testing", ar: "اختبار الإعلانات" }, number: "03" },
  ],
  heroBottomBarText: {
    en: "Brand + Content + Campaigns",
    ar: "هوية + محتوى + حملات",
  },
  heroSignalLabel: {
    en: "Panda Signal",
    ar: "إشارة باندا",
  },
  heroSignalTitle: {
    en: "Strategy-led creative",
    ar: "استراتيجية تقود الإبداع",
  },
  statsEyebrow: {
    en: "Measured Creative Impact",
    ar: "أثر قابل للقياس",
  },
  statsHeadline: {
    en: "Numbers behind clearer brand momentum.",
    ar: "أرقام تتحرك خلف قصة أوضح.",
  },
  stats: [
    { id: "s1", value: 250, prefix: "+", label: { en: "Campaigns launched", ar: "حملة أطلقت" } },
    { id: "s2", value: 120, prefix: "+", label: { en: "Brands shipped", ar: "علامة تم تطويرها" } },
    { id: "s3", value: 5, suffix: "M+", label: { en: "Organic + paid reach", ar: "وصول عضوي ومدفوع" } },
    { id: "s4", value: 98, suffix: "%", label: { en: "Client satisfaction", ar: "رضا العملاء" } },
  ],
  servicesHeadline: { en: "", ar: "" },
  finalCtaTitle: {
    en: "Let's build your growth system.",
    ar: "لنبنِ نظام نموك.",
  },
  finalCtaSub: {
    en: "Tell us about your brand. We'll come back with a strategic point of view within 48 hours.",
    ar: "أخبرنا عن علامتك. سنعود إليك برأي استراتيجي خلال 48 ساعة.",
  },
};

export const defaultServices: ServiceItem[] = [
  {
    id: "svc-social",
    slug: "social",
    number: "01",
    icon: "MonitorSmartphone",
    image: "/assets/services/social-media-planning.jpg",
    title: { en: "Social Media Management", ar: "إدارة وسائل التواصل الاجتماعي" },
    desc: {
      en: "Always-on content systems that build authority, engagement, and customer trust.",
      ar: "أنظمة محتوى مستمرة تبني الحضور، التفاعل، وثقة العملاء.",
    },
    note: {
      en: "Content systems that stay consistent and earn trust.",
      ar: "أنظمة محتوى مستمرة تبني الثقة.",
    },
    tags: { en: ["Calendars", "Captions"], ar: ["تقويم", "نصوص"] },
    bullets: {
      en: ["Monthly content calendars", "Copywriting and captions", "Community management", "Competitor monitoring", "Monthly reports"],
      ar: ["تقويم محتوى شهري", "كتابة النصوص والتعليقات", "إدارة المجتمع", "متابعة المنافسين", "تقارير شهرية"],
    },
    bestFor: {
      en: ["Restaurants", "Cafes", "Retail brands", "Service businesses"],
      ar: ["مطاعم", "مقاهي", "علامات تجزئة", "شركات خدمات"],
    },
    featured: true,
    active: true,
    order: 1,
  },
  {
    id: "svc-branding",
    slug: "branding",
    number: "02",
    icon: "Sparkles",
    image: "/assets/services/brand-identity-system.jpg",
    title: { en: "Branding & Identity", ar: "العلامة والهوية" },
    desc: {
      en: "Brand systems that make businesses recognizable, trusted, and easier to sell.",
      ar: "أنظمة علامة تجعل الأعمال أكثر وضوحا وثقة وأسهل في البيع.",
    },
    note: {
      en: "Positioning and identity that make the business easier to choose.",
      ar: "تموضع وهوية تجعل الاختيار أسهل.",
    },
    tags: { en: ["Identity", "Messaging"], ar: ["هوية", "رسائل"] },
    bullets: {
      en: ["Logo and visual identity", "Brand guidelines", "Brand positioning", "Naming and messaging", "Brand personality"],
      ar: ["الشعار والهوية البصرية", "دليل استخدام العلامة", "تموضع العلامة", "التسمية والرسائل", "شخصية العلامة"],
    },
    bestFor: {
      en: ["New businesses", "Rebrands", "Premium launches"],
      ar: ["مشاريع جديدة", "إعادة بناء الهوية", "إطلاقات فاخرة"],
    },
    featured: false,
    active: true,
    order: 2,
  },
  {
    id: "svc-content",
    slug: "content",
    number: "03",
    icon: "Layers",
    image: "/assets/services/content-production-studio.jpg",
    title: { en: "Content Production", ar: "إنتاج المحتوى" },
    desc: {
      en: "Photography, reels, TikTok videos, campaign visuals, and creative assets built for performance.",
      ar: "تصوير، ريلز، فيديوهات تيك توك، مرئيات حملات، ومواد إبداعية مبنية للأداء.",
    },
    note: {
      en: "Photography, reels, and campaign assets with a point of view.",
      ar: "تصوير وريلز ومواد حملة برؤية واضحة.",
    },
    tags: { en: ["Reels", "Campaigns"], ar: ["ريلز", "حملات"] },
    bullets: {
      en: ["Product photography", "Reels and short-form videos", "Social media designs", "Campaign concepts", "Smart trend usage"],
      ar: ["تصوير المنتجات", "ريلز وفيديوهات قصيرة", "تصاميم السوشيال", "أفكار حملات", "استخدام ذكي للترند"],
    },
    bestFor: {
      en: ["Food brands", "Restaurants", "Product businesses", "Campaigns"],
      ar: ["علامات الطعام", "مطاعم", "منتجات", "حملات"],
    },
    featured: false,
    active: true,
    order: 3,
  },
  {
    id: "svc-paid",
    slug: "paid",
    number: "04",
    icon: "LineChart",
    image: "/assets/services/paid-media-analytics.jpg",
    title: { en: "Paid Media", ar: "الإعلانات المدفوعة" },
    desc: {
      en: "Performance campaigns designed to reach the right audience and improve conversion.",
      ar: "حملات أداء مصممة للوصول للجمهور الصحيح وتحسين التحويل.",
    },
    note: {
      en: "Performance campaigns refined by data and creative testing.",
      ar: "حملات أداء مدعومة بالبيانات والاختبار.",
    },
    tags: { en: ["Meta", "Retargeting"], ar: ["ميتا", "استهداف"] },
    bullets: {
      en: ["Meta ads", "TikTok ads", "Retargeting", "Campaign optimization", "Performance reporting"],
      ar: ["إعلانات ميتا", "إعلانات تيك توك", "إعادة الاستهداف", "تحسين الحملات", "تقارير الأداء"],
    },
    bestFor: {
      en: ["Sales campaigns", "Launches", "Lead generation"],
      ar: ["حملات بيع", "إطلاقات", "توليد عملاء محتملين"],
    },
    featured: false,
    active: true,
    order: 4,
  },
  {
    id: "svc-offline",
    slug: "offline",
    number: "05",
    icon: "Megaphone",
    image: "/assets/services/offline-campaign-event.jpg",
    title: { en: "Offline Marketing", ar: "التسويق الميداني" },
    desc: {
      en: "On-ground campaigns and printed marketing materials that complete the brand experience.",
      ar: "حملات ميدانية ومواد مطبوعة تكمل تجربة العلامة.",
    },
    note: {
      en: "On-ground moments that make the brand tangible.",
      ar: "تجارب ميدانية تجعل العلامة ملموسة.",
    },
    tags: { en: ["Events", "Print"], ar: ["فعاليات", "طباعة"] },
    bullets: {
      en: ["Field campaigns", "Seasonal campaigns", "Influencer collaborations", "Print materials", "Radio / TV ad coordination"],
      ar: ["حملات ميدانية", "حملات موسمية", "تعاون مع مؤثرين", "مواد مطبوعة", "تنسيق إعلانات راديو وتلفزيون"],
    },
    bestFor: {
      en: ["Local campaigns", "Events", "Seasonal promotions"],
      ar: ["حملات محلية", "فعاليات", "عروض موسمية"],
    },
    featured: false,
    active: true,
    order: 5,
  },
];

export const defaultPortfolio: PortfolioItem[] = [
  {
    id: "p1",
    slug: "metro-ooh",
    title: { en: "Restaurant Launch Campaign", ar: "حملة إطلاق مطعم" },
    category: "offline",
    image: "/assets/portfolio/restaurant-launch-campaign.jpg",
    video: "/assets/portfolio/videos/restaurant-launch-campaign.mp4",
    type: "video",
    impact: { en: "A launch campaign built to create local buzz and first-week footfall.", ar: "حملة إطلاق صممت لصناعة حضور محلي وزيارات قوية في الأسبوع الأول." },
    challenge: { en: "Build immediate awareness in a crowded dining market.", ar: "بناء وعي سريع في سوق مطاعم مزدحم." },
    strategy: { en: "Combined launch content, local creators, outdoor visibility, and offer-led media.", ar: "دمجنا محتوى الإطلاق، المؤثرين المحليين، الظهور الخارجي، وإعلانات العروض." },
    result: { en: "Strong launch recall and a campaign system ready for seasonal reuse.", ar: "حضور إطلاق قوي ونظام حملة قابل للتكرار موسميا." },
    featured: true,
    active: true,
    order: 1,
  },
  {
    id: "p2",
    slug: "north-social",
    title: { en: "Cafe Social Media System", ar: "نظام سوشيال ميديا لمقهى" },
    category: "social",
    image: "/assets/portfolio/cafe-social-system.jpg",
    video: "/assets/portfolio/videos/cafe-social-system.mp4",
    type: "video",
    impact: { en: "A consistent content rhythm for daily community engagement.", ar: "إيقاع محتوى مستمر لبناء تفاعل يومي مع الجمهور." },
    challenge: { en: "Move beyond random posting into a repeatable content engine.", ar: "الانتقال من النشر العشوائي إلى نظام محتوى متكرر." },
    strategy: { en: "Created monthly pillars, caption direction, reels concepts, and reporting cadence.", ar: "بنينا محاور شهرية، اتجاه كتابة، أفكار ريلز، ونظام تقارير." },
    result: { en: "Cleaner feed, stronger brand memory, and easier monthly production.", ar: "حساب أوضح، تذكر أقوى للعلامة، وإنتاج شهري أسهل." },
    featured: false,
    active: true,
    order: 2,
  },
  {
    id: "p3",
    slug: "atlas-rebrand",
    title: { en: "Retail Brand Identity", ar: "هوية علامة تجزئة" },
    category: "branding",
    image: "/assets/portfolio/retail-brand-identity.jpg",
    type: "image",
    impact: { en: "A more recognizable identity system for retail expansion.", ar: "نظام هوية أوضح وأكثر قابلية للتوسع في التجزئة." },
    featured: false,
    active: true,
    order: 3,
  },
  {
    id: "p4",
    slug: "noir-launch",
    title: { en: "Product Photography Campaign", ar: "حملة تصوير منتجات" },
    category: "content",
    image: "/assets/portfolio/product-photography-campaign.jpg",
    type: "image",
    impact: { en: "Product visuals shaped for launch pages, ads, and social content.", ar: "صور منتجات مصممة لصفحات الإطلاق والإعلانات والسوشيال." },
    featured: false,
    active: true,
    order: 4,
  },
  {
    id: "p5",
    slug: "paid-ads-growth",
    title: { en: "Paid Ads Growth Campaign", ar: "حملة نمو بالإعلانات المدفوعة" },
    category: "ads",
    image: "/assets/portfolio/paid-ads-growth-campaign.jpg",
    video: "/assets/portfolio/videos/paid-ads-growth-campaign.mp4",
    type: "video",
    impact: { en: "Creative testing and retargeting built around clearer conversion paths.", ar: "اختبار إبداعي وإعادة استهداف حول مسارات تحويل أوضح." },
    featured: false,
    active: true,
    order: 5,
  },
  {
    id: "p6",
    slug: "seasonal-offline",
    title: { en: "Seasonal Offline Campaign", ar: "حملة ميدانية موسمية" },
    category: "offline",
    image: "/assets/portfolio/seasonal-offline-campaign.jpg",
    type: "image",
    impact: { en: "A field activation system connecting print, creators, and on-ground teams.", ar: "نظام تفعيل ميداني يربط الطباعة، المؤثرين، والفرق على الأرض." },
    featured: false,
    active: true,
    order: 6,
  },
  {
    id: "p7",
    slug: "fazion-editorial",
    title: { en: "Reels Content Package", ar: "باقة محتوى ريلز" },
    category: "content",
    image: "/assets/portfolio/reels-content-package.jpg",
    video: "/assets/portfolio/videos/reels-content-package.mp4",
    type: "video",
    impact: { en: "Short-form content designed for attention, retention, and reuse.", ar: "محتوى قصير مصمم للانتباه والاستمرارية وإعادة الاستخدام." },
    featured: false,
    active: true,
    order: 7,
  },
  {
    id: "p8",
    slug: "verde-identity",
    title: { en: "Brand Repositioning Project", ar: "مشروع إعادة تموضع علامة" },
    category: "branding",
    image: "/assets/portfolio/brand-repositioning-project.jpg",
    type: "image",
    impact: { en: "A clearer story, sharper identity, and more premium market language.", ar: "قصة أوضح، هوية أدق، ولغة سوقية أكثر فخامة." },
    featured: false,
    active: true,
    order: 8,
  },
];

export const defaultTestimonials: Testimonial[] = [
  {
    id: "t1",
    quote: {
      en: "Panda rebuilt our funnel from strategy to execution. Six months later, acquisition became clearer, calmer, and far more efficient.",
      ar: "أعاد فريق باندا بناء مسارنا من الاستراتيجية إلى التنفيذ. بعد ستة أشهر أصبح الاستحواذ أوضح وأكثر كفاءة.",
    },
    author: { en: "Layla Haddad", ar: "ليلى حداد" },
    role: { en: "CMO, Restaurant Group", ar: "مديرة التسويق، مجموعة مطاعم" },
    active: true,
    order: 1,
  },
  {
    id: "t2",
    quote: {
      en: "They operate like a senior in-house growth team: strategic, fast, and careful with every brand detail.",
      ar: "يتعاملون كفريق نمو داخلي خبير: استراتيجيون، سريعون، ودقيقون في كل تفصيل للعلامة.",
    },
    author: { en: "Omar Khalil", ar: "عمر خليل" },
    role: { en: "Founder, Retail Market", ar: "مؤسس، علامة تجزئة" },
    active: true,
    order: 2,
  },
  {
    id: "t3",
    quote: {
      en: "The brand work felt premium from day one. The strategy was clear, and the creative system was easy for our team to use.",
      ar: "شعرنا بفخامة العمل منذ اليوم الأول. الاستراتيجية واضحة، والنظام الإبداعي سهل الاستخدام لفريقنا.",
    },
    author: { en: "Sara Mansour", ar: "سارة منصور" },
    role: { en: "Marketing Lead, Beauty Clinic", ar: "قائدة التسويق، عيادة تجميل" },
    active: true,
    order: 3,
  },
];

export const defaultBrands: Brand[] = [
  {
    id: "b1",
    name: "Restaurant Brand",
    logo: "/assets/brands/restaurant-brand.svg",
    category: { en: "Restaurant", ar: "مطاعم" },
    story: { en: "Launch campaign", ar: "حملة إطلاق" },
    active: true,
    order: 1,
  },
  {
    id: "b2",
    name: "Cafe Group",
    logo: "/assets/brands/cafe-group.svg",
    category: { en: "Cafe", ar: "مقاهي" },
    story: { en: "Social content system", ar: "نظام محتوى اجتماعي" },
    active: true,
    order: 2,
  },
  {
    id: "b3",
    name: "Beauty Clinic",
    logo: "/assets/brands/beauty-clinic.svg",
    category: { en: "Clinic", ar: "عيادة" },
    story: { en: "Brand identity refresh", ar: "تحديث الهوية" },
    active: true,
    order: 3,
  },
  {
    id: "b4",
    name: "Fashion Store",
    logo: "/assets/brands/fashion-store.svg",
    category: { en: "Fashion", ar: "أزياء" },
    story: { en: "Editorial campaign", ar: "حملة تحريرية" },
    active: true,
    order: 4,
  },
  {
    id: "b5",
    name: "Retail Market",
    logo: "/assets/brands/retail-market.svg",
    category: { en: "Retail", ar: "تجزئة" },
    story: { en: "Paid media growth", ar: "نمو الإعلانات" },
    active: true,
    order: 5,
  },
  {
    id: "b6",
    name: "Wellness Studio",
    logo: "/assets/brands/wellness-studio.svg",
    category: { en: "Wellness", ar: "عافية" },
    story: { en: "Visual identity system", ar: "نظام هوية بصرية" },
    active: true,
    order: 6,
  },
  {
    id: "b7",
    name: "Local Campaign",
    logo: "/assets/brands/local-campaign.svg",
    category: { en: "Campaign", ar: "حملة محلية" },
    story: { en: "Offline activation", ar: "تفعيل ميداني" },
    active: true,
    order: 7,
  },
];

export const defaultAboutContent: AboutContent = {
  heroTitle: {
    en: "We are Panda - a strategy-led creative marketing agency.",
    ar: "نحن باندا — وكالة تسويق إبداعية تقودها الاستراتيجية.",
  },
  heroSubtitle: {
    en: "We help ambitious brands build identity, content, campaigns, and communication systems that make growth more intentional.",
    ar: "نساعد العلامات التجارية الطموحة على بناء الهوية، المحتوى، الحملات، وأنظمة التواصل التي تجعل النمو أكثر وضوحًا وتنظيمًا.",
  },
  storyText: {
    en: "Panda Marketing Agency was built for businesses that need more than random posts and temporary campaigns. From Hebron, we work with brands to create clear identities, consistent content, smart campaigns, and marketing systems that connect creativity with business results.",
    ar: "تأسست وكالة باندا للتسويق لخدمة الشركات التي تحتاج إلى ما هو أعمق من منشورات عشوائية أو حملات مؤقتة. من الخليل، نعمل مع العلامات التجارية لبناء هويات واضحة، محتوى متناسق، حملات ذكية، وأنظمة تسويقية تربط الإبداع بالنتائج التجارية.",
  },
  mission: {
    en: "To engineer marketing that actually moves the business.",
    ar: "هندسة تسويق يحرّك العمل فعلاً.",
  },
  vision: {
    en: "To be the most trusted growth partner for ambitious brands in the region.",
    ar: "أن نكون شريك النمو الأكثر ثقة للعلامات الطموحة في المنطقة.",
  },
  values: [
    { en: "Strategy before execution", ar: "الاستراتيجية قبل التنفيذ" },
    { en: "Creativity with purpose", ar: "الإبداع له هدف" },
    { en: "Consistency builds trust", ar: "الاستمرارية تبني الثقة" },
    { en: "Results guide decisions", ar: "النتائج تقود القرارات" },
  ],
  teamImage: "/assets/about/creative-studio-team.jpg",
};

// Password is base64-encoded "panda2024" — replace with a real hash when backend is added.
export const defaultSettings: SiteSettings = {
  companyName: "Panda Marketing Agency",
  phone: "+972 597 228 693",
  email: "panda.marketing111@gmail.com",
  location: { en: "Hebron, Palestine", ar: "الخليل، فلسطين" },
  instagramUrl: "",
  facebookUrl: "",
  twitterUrl: "",
  linkedinUrl: "",
  seoTitle: "Panda Marketing Agency — Strategy. Brand. Growth.",
  seoDescription: "Panda is a strategy-led creative agency partnering with ambitious brands across the region.",
  logoText: "PANDA",
  adminUsername: (import.meta.env.VITE_ADMIN_EMAIL as string) || "",
  adminPasswordHash: (import.meta.env.VITE_ADMIN_PASSWORD_HASH as string) || "",
};
